name: Code Coverage

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}

    strategy:
      matrix:
        otp: [21.x, 22.x, 23.x]
        elixir: [1.8.x, 1.9.x, 1.10.x, 1.11.x]

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: erlef/setup-elixir@v1.7
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}


      - name: Cache Dependencies
        uses: actions/cache@v2.1.4
        with:
          path: deps
          key: deps-elixir-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-${{github.ref}}
          restore-keys: |
            deps-elixir-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-${{github.ref}}
            deps-elixir-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-

      - name: Cache Test Build
        uses: actions/cache@v2.1.4
        with:
          path: _build/test
          key: test-build-elixir-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-${{github.ref}}
          restore-keys: |
            test-build-elixir-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-${{github.ref}}
            test-build-elixir-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-

      - name: Install Dependencies
        run: mix deps.get

      - name: Coveralls
        env:
          MIX_ENV: test
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BITMEX_API_KEY: ${{secrets.BITMEX_API_KEY}}
          BITMEX_API_SECRET: ${{secrets.BITMEX_API_SECRET}}
        run: mix coveralls.github
